### ISSUE TITLE
토큰이 없어서 로그인이 불가능한 문제

### ISSUE THREAD

**Issue by jin20fd** [TogetherWithOcean-TWO/Back#40]
로그인 시, 403 오류 발생...
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/d4610289-1a73-40aa-87e5-f22dbea35234">

<br>

서버에서 찍힌 로그
```
액세스 토큰: null
리프레쉬 토큰: null
유효하지 않은 토큰
```

나도 왜이런지가 모르겠어서... 같이 찾아봅시다

**Comment by KSJ0128** [comment]
..? 로그인 되는뎁쇼
403인거보니까 저때는 데이터가 없었던 거 아닐까..? 아니면 중복..? 암튼 지금 돼용

**Comment by jin20fd** [comment]
ㅜ머지 난왜안될까...

**Comment by KSJ0128** [comment]
redis를 백그라운드 실행하며 해결
